# Site Settings
title: Kevin McDermott
email: kevin.t.mcdermott@gmail.com
description: "Computerphile // Hacker // Snowboarder"
name: Kevin McDermott
markdown: kramdown
permalink: /blog/:year/:month/:day/:title